const projects = [
  {
    "id": 1,
    "title": "Jenda @OKsystem",
    "blurb": "An app for digitising benefit applications for the Czech Ministry of Labour and Social Affairs.",
    "short_description": "An app for digitalizing benefit applications for the Czech Ministry of Labour and Social Affairs.",
    "long_description": "Jenda enables citizens to apply for various benefits from their homes, saving them time and effort. Working on this project has been enriching, allowing me to collaborate with a large team and deal with complex data and forms.",
    "my_role": "Front-end developer",
    "duration": "2023",
    "tools": "IntelliJ IDEA, Bitbucket, Figma",
    "technologies": "React.js, Typescript, JavaScript, CSS",
    "libraries": "Tailwind CSS, React Hook Form, Yup",
    "what_i_learned": "This project has been the most enriching experience for me. It's my first time working with a large team of analytics, UX designers, and engineers. I've also learned to work with shared components and handle complex forms using React Hook Form.",
    "features": "Benefits application forms, Data handling, Form validation",
    imageUrl: "https://github.com/KatBuxton/portfolio/assets/101291722/c550cac2-667a-4e96-8bf5-8db5dc60f32b",
    "webUrl": "https://jenda.mpsv.cz/",
  },
  {
    "id": 2,
    "title": "Baby-friendly.cz",
    blurb: " This is my first web app, it was created as a final project for Czechitas Digital Academy. Of course, it's far from perfect, but I am proud of being able to present a working, scalable, monetizable product only a few months after writing my first line of code.",
    "short_description": "Map of baby-friendly places in Prague & Czech Republic.",
    "long_description": "Baby-friendly.cz is a web application designed to help parents find baby-friendly places in Prague and the Czech Republic. It allows users to search for places, filter by type, and provides information on baby facilities. The project was created as a final project for Czechitas Digital Academy, marking my entry into the world of web development.",
    "my_role": "Creator, UX designer, Developer",
    "duration": "March 2022 - June 2022",
    "tools": "VS Code, Github, Figma, Netlify",
    "technologies": "React.js, JavaScript, CSS",
    "libraries": "React Map GL",
    "what_i_learned": "I learned the importance of using a good quality roadmap to track progress and plan next steps. I also gained insights into the value of user feedback and addressing personal biases in design. Working with mentors and tutors from Czechitas taught me to ask good questions and take inspiration from talented people.",
    "case_study": "https://www.canva.com/design/DAFDZTDKWKM/m9AnoXdW4gfAEw-pdGOidA/view?utm_content=DAFDZTDKWKM&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink",
    "repo": "https://github.com/KatBuxton/Babyfriendly",
    imageUrl:"https://user-images.githubusercontent.com/101291722/173179935-6d8ebfd4-ff95-4ec8-b6c6-3eae1b67faac.png",
    webUrl: "https://www.baby-friendly.cz"
  },
  {
    "id": 3,
    "title": "Wake on LAN @OKsystem",
    blurb:
        'My first project as a front-end developer at OKsystem. This app is intended for internal purposes; a logged-in user can add, edit and delete his computers and send a magic packet that wakes his computer up.',
    "short_description": "An app for waking up your computer remotely.",
    "long_description": "Wake on LAN @OKsystem is my first project as a frontend developer at OKsystem. It allows logged-in users to add, edit, and delete their computers and send a magic packet to wake up their computer remotely.",
    "my_role": "UX designer, Front-end developer",
    "duration": "February 2023 - April 2023",
    "tools": "IntelliJ IDEA, Bitbucket, Figma",
    "technologies": "React.js, Typescript, JavaScript, CSS",
    "libraries": "Tailwind CSS, Zustand, Day.js, Yup, Formik, React Hook Form, React Helmet",
    "what_i_learned": "I learned a lot while working on this project, including using Tailwind, Zustand, and many other libraries. I also faced the challenge of working with backend API calls and managing state with Zustand.",
    "features": "Remote computer wake-up",
    imageUrl:"https://github.com/KatBuxton/portfolio/assets/101291722/95985d42-7f1f-48c1-8c17-905f75ce7ec2",
  },
  {
    "id": 4,
    "title": "JWT explorer @OKsystem",
    "blurb": "Simplifying access to testing and dev environments by generating JWTs.",
    "short_description": "Simplifying access to testing and dev environments by generating JWTs.",
    "long_description": "JWT explorer @OKsystem simplifies accessing testing and development environments by generating JSON Web Tokens (JWTs) and decoding them. Originally intended as a simple project, it grew in scope to include user filtering functionality.",
    "my_role": "UX designer, Front-end developer",
    "duration": "August 2023 - September 2023",
    "tools": "IntelliJ IDEA, Bitbucket, Figma",
    "technologies": "React.js, Typescript, JavaScript, CSS",
    "libraries": "Tailwind CSS, React Hook Form, Radix, Toastify",
    "what_i_learned": "The challenge of this project was its changing scope, which taught me flexibility and adaptability. I also had the opportunity to practice using React Hook Form and creating complex user-filtering components.",
    "features": "JWT generation and decoding, User filtering",
    imageUrl: "https://github.com/KatBuxton/portfolio/assets/101291722/d0a4a9d1-c896-4952-9395-fe2566dbc6a7",
  },
  {
    "id": 5,
    "title": "Natural cosmetics shop",
    blurb: 'This website is a minimalistic e-shop for promoting natural cosmetic products which are hand-made by my sister, Sabina. The website is fully responsive and anyone can browse the products, add them to cart and place an order.',
    "short_description": "An e-shop with natural cosmetic products.",
    "long_description": "Prirodni kosmetika is a minimalistic e-shop for promoting natural cosmetic products handmade by my sister Sabina. Users can browse products, add them to the cart, and place orders. Although not fully finished, with some SEO and social media marketing, this business could be discovered by its first customers.",
    "my_role": "Creator, UX designer, Developer",
    "duration": "November 2022 - December 2022",
    "tools": "VS Code, Github, Figma, Netlify",
    "technologies": "React.js, JavaScript, CSS",
    "libraries": "Email.js, Context",
    "what_i_learned": "I worked on this project mostly independently, which taught me to use online resources effectively and find alternative solutions. It was also my first project using Context for state management.",
    "features": "Filtering by product category, Add to cart, Place an order",
    repo: "https://github.com/KatBuxton/prirodni-kosmetika",
    imageUrl:"https://user-images.githubusercontent.com/101291722/273207000-631d6bca-1c38-4b91-8559-46aa87413e4c.jpg",
    webUrl: "https://sabinky-obchod.netlify.app/"
  },

  {
    "id": 6,
    "title": "Standardised meal plan",
    "blurb": "A recipe and ingredient shopping app for a standardised meal system.",
    "short_description": "A recipe and ingredient shopping app for a standardised meal system.",
    "long_description": "This app is designed to simplify meal planning and grocery shopping by implementing a standardised meal system. It offers nutritious, easy-to-make meals with mild variations based on ingredient availability, reducing supermarket spending and kitchen time.",
    "my_role": "UX designer, Front-end developer",
    "duration": "April 2023 - May 2023",
    "tools": "IntelliJ IDEA, Github, Figma",
    "technologies": "React.js, Typescript, JavaScript, CSS",
    "libraries": "Tailwind CSS",
    "what_i_learned": "I learned the importance of image optimiastion and using responsive images for performance and accessibility. This project also allowed me to apply my knowledge of front-end development to solve real-life challenges. Although still in progress, this app is already used in our household every day, saving us some valuable time and mental capacity.",
    "features": "Recipe display, Meal planning, Ingredient shopping list",
    repo:"https://github.com/KatBuxton/standardised-meal-plan",
    imageUrl:"https://github.com/KatBuxton/portfolio/assets/101291722/bd2ba479-d5c3-47d2-9386-640daa57b51c",
    webUrl: "https://standardised-meal-plan.netlify.app/",
  },

];

export default projects;
